"""Regenerate papers/MANIFEST.md from the corpus on disk + the source registry.

The reference corpus (copyrighted PDFs) is not committed; this manifest is what makes it
*reproducible and auditable* — each row records the file, its size, a SHA-256 prefix, its DOI,
and the registry source_label it feeds (so any reader can retrieve each item legitimately and
verify it). Regenerate after adding papers:

    python -m geomind.manifest        # rewrites papers/MANIFEST.md from what is on disk

DOI resolution, in order of trust: the DOI printed on the paper's own first page (self-evidently
correct); then a small curated map for items whose DOI is not machine-extractable (theses, older
proceedings) or must be forced; otherwise `_TBD_`. The source_label column is filled by matching a
row's DOI against the registry, tying each file to the data rows it supports.
"""
from __future__ import annotations

import hashlib
import re
import warnings
from pathlib import Path

import yaml

_ROOT = Path(__file__).resolve().parents[2]
REFS = _ROOT / "papers" / "references"
MAIN = _ROOT / "papers" / "main"
REGISTRY = _ROOT / "knowledge_base" / "registry.yaml"
OUT = _ROOT / "papers" / "MANIFEST.md"

#: DOIs / identifiers that are not extractable from the PDF first page, or must be forced.
_CURATED: dict[str, str] = {
    "Hossain-2026-composition-properties-adsorption-AAM.pdf": "10.1016/j.matdes.2026.115471",
    "822897.pdf": "ISBN 978-3-95806-559-8 (RWTH/FZJ dissertation, 2020)",
    "perera2004.pdf": "MRS Symp. Proc. 824, CC8.35 (2004)",
    "Muracchioli_Mattia_1128630.pdf": "MSc thesis, Univ. Padua (2019)",
}


def _sha16(p: Path) -> str:
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()[:16]


def _doi_from_pdf(p: Path) -> str:
    if p.suffix.lower() != ".pdf":
        return ""
    try:
        import pdfplumber
        with pdfplumber.open(p) as pdf:
            txt = "".join((pdf.pages[i].extract_text() or "")
                          for i in range(min(2, len(pdf.pages))))
    except Exception:
        return ""
    m = re.search(r"10\.\d{4,9}/[^\s,;)\]\"']+", txt)
    return m.group(0).rstrip(".").rstrip(")") if m else ""


def _doi_to_label() -> dict[str, str]:
    reg = yaml.safe_load(REGISTRY.read_text())
    out = {}
    for s in reg.get("sources", []):
        doi = s.get("doi")
        if doi:
            out[str(doi).lower()] = s["id"]
    return out


def build_rows() -> list[dict]:
    warnings.filterwarnings("ignore")
    doi2label = _doi_to_label()
    rows = []
    for area, label in ((MAIN, "MAIN"), (REFS, "REF")):
        if not area.exists():
            continue
        for f in sorted(area.iterdir(), key=lambda x: x.name.lower()):
            if not f.is_file():
                continue
            # Saved publisher web pages (.html) are not citable corpus documents — they are
            # redundant copies of papers held elsewhere as PDFs, and are the copyrighted-page
            # category excluded from git. Do not catalogue them.
            if f.suffix.lower() in {".html", ".htm"}:
                continue
            doi = _CURATED.get(f.name) or _doi_from_pdf(f)
            src = doi2label.get(doi.lower(), "") if doi else ""
            rows.append({
                "type": label,
                "file": f.name,
                "mb": round(f.stat().st_size / 1e6, 2),
                "sha16": _sha16(f),
                "doi": doi or "_TBD_",
                "source": src,
            })
    return rows


def render(rows: list[dict]) -> str:
    n = len(rows)
    with_doi = sum(1 for r in rows if r["doi"] != "_TBD_")
    linked = sum(1 for r in rows if r["source"])
    lines = [
        "# Literature Corpus — Manifest",
        "",
        "> **Files are NOT committed.** These are copyrighted publications held as personal",
        "> research copies (see `.gitignore`). This manifest makes the corpus *reproducible and",
        "> auditable* — retrieve each item from its source, then verify the SHA-256 prefix.",
        "",
        "> Generated by `python -m geomind.manifest` from the corpus on disk and the source",
        "> registry. Do not hand-edit — re-run the generator after adding papers.",
        "",
        f"_{n} documents on disk · {with_doi} with a resolved DOI/identifier · "
        f"{linked} linked to a registry `source_label`._",
        "",
        "| # | Type | File | MB | SHA-256 (16) | DOI / identifier | source_label |",
        "|---|------|------|----|--------------|------------------|--------------|",
    ]
    for i, r in enumerate(rows, 1):
        lines.append(
            f"| {i} | {r['type']} | `{r['file']}` | {r['mb']} | `{r['sha16']}` | "
            f"{r['doi']} | {r['source'] or '—'} |")
    lines += [
        "",
        "## Associated datasets",
        "",
        "| Dataset | Location | Companion paper |",
        "|---|---|---|",
        "| Oulu AAM synthesis / characterisation / adsorption | `data/external/aam-oulu-2026/` "
        "*(not committed)* | 10.1016/j.matdes.2026.115471 |",
        "",
        "## Notes",
        "",
        "- **Reference work under replication:** *GEOMIND*, RSC **Digital Discovery** (2026), "
        "DOI [10.1039/d5dd00383k](https://doi.org/10.1039/d5dd00383k), CC-BY-NC 4.0 — cited "
        "throughout; held locally, not redistributed here.",
        "- **`source_label`** links a file to the rows it supports in the audited pools; `—` means "
        "the paper is cited for context/mechanism (or is out of scope) and contributes no data row.",
        "- **`_TBD_`** marks a file whose DOI is not machine-extractable and not yet curated; the "
        "corpus stays auditable via the SHA-256 prefix regardless. Every compiled data row must "
        "still trace to an entry here.",
    ]
    return "\n".join(lines) + "\n"


def build() -> str:
    rows = build_rows()
    OUT.write_text(render(rows))
    return str(OUT)


def main() -> None:  # pragma: no cover - CLI convenience
    print("wrote", build(), f"({len(build_rows())} documents)")


if __name__ == "__main__":  # pragma: no cover
    main()
